package apply

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/convergent-systems-co/branding-library/src/brandatom/internal/client"
)

// EmitAndroid writes app/src/main/res/values/brand-atoms.xml with one
// `<color>` resource per canonical role. The file slots into the
// existing Android resource pipeline — no Gradle changes needed.
func EmitAndroid(brand *client.ResolvedBrand, projectRoot string) PlannedWrite {
	dest := filepath.Join(projectRoot, "app", "src", "main", "res", "values", "brand-atoms.xml")

	var b strings.Builder
	b.WriteString(`<?xml version="1.0" encoding="utf-8"?>` + "\n")
	fmt.Fprintf(&b, "<!-- brand-atoms.xml — %s@%s\n     Generated by brandatom. -->\n", brand.ID, brand.Version)
	b.WriteString("<resources>\n")

	roles := []struct {
		resName string
		roleKey string
	}{
		{"brandatom_primary", "primary"},
		{"brandatom_accent", "accent"},
		{"brandatom_identity", "identity"},
		{"brandatom_surface", "surface"},
		{"brandatom_background", "background"},
		{"brandatom_text_primary", "text-primary"},
	}
	for _, r := range roles {
		hex := brand.RoleHex(r.roleKey, "light")
		if hex == "" && r.roleKey == "identity" {
			hex = brand.RoleHex("primary", "light")
		}
		if hex == "" {
			continue
		}
		// Android wants #AARRGGBB or #RRGGBB. The encyclopedia produces
		// #RRGGBB or #RRGGBBAA — Android's hex order differs (alpha
		// first, not last). Drop alpha rather than reorder; ANSI swatches
		// already do this and matching keeps the two outputs aligned.
		fmt.Fprintf(&b, "    <color name=\"%s\">%s</color>\n", r.resName, dropAlpha(hex))
	}
	b.WriteString("</resources>\n")

	return PlannedWrite{
		Path:     dest,
		Contents: []byte(b.String()),
		Kind:     "android",
	}
}

func dropAlpha(hex string) string {
	hex = strings.TrimPrefix(hex, "#")
	if len(hex) == 8 {
		hex = hex[:6]
	}
	return "#" + hex
}
