package apply

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/convergent-systems-co/branding-library/src/brandatom/internal/client"
)

// EmitSwift writes a Brand.swift file next to the .xcodeproj. The output
// defines a `BrandAtoms` enum with static UIColor properties for the
// canonical roles. UIKit only — SwiftUI consumers can wrap as needed.
func EmitSwift(brand *client.ResolvedBrand, xcodeprojPath string) PlannedWrite {
	// xcodeprojPath is the .xcodeproj directory. We write next to it,
	// not inside it (Xcode never auto-includes loose files in subdirs).
	parent := filepath.Dir(xcodeprojPath)
	dest := filepath.Join(parent, "Brand.swift")

	var b strings.Builder
	fmt.Fprintf(&b, "// Brand.swift — %s@%s\n", brand.ID, brand.Version)
	b.WriteString("// Generated by brandatom. Drag into Xcode to expose `BrandAtoms.primary`.\n\n")
	b.WriteString("import UIKit\n\n")
	b.WriteString("public enum BrandAtoms {\n")

	roles := []struct {
		swiftName string
		roleKey   string
	}{
		{"primary", "primary"},
		{"accent", "accent"},
		{"identity", "identity"},
		{"surface", "surface"},
		{"background", "background"},
		{"textPrimary", "text-primary"},
	}
	for _, r := range roles {
		hex := brand.RoleHex(r.roleKey, "light")
		if hex == "" && r.roleKey == "identity" {
			hex = brand.RoleHex("primary", "light")
		}
		if hex == "" {
			continue
		}
		fmt.Fprintf(&b, "    public static let %s = UIColor(red: %s, green: %s, blue: %s, alpha: 1.0)\n",
			r.swiftName,
			swiftChannel(hex, 0),
			swiftChannel(hex, 1),
			swiftChannel(hex, 2),
		)
	}
	b.WriteString("}\n")

	return PlannedWrite{
		Path:     dest,
		Contents: []byte(b.String()),
		Kind:     "swift",
	}
}

// swiftChannel returns the R/G/B channel value (0..1) of a hex color
// formatted to four decimal places — Swift's compiler accepts this
// without complaint and humans can still read it.
func swiftChannel(hex string, idx int) string {
	hex = strings.TrimPrefix(hex, "#")
	if len(hex) < 6 {
		return "0.0"
	}
	pair := hex[idx*2 : idx*2+2]
	var v int
	if _, err := fmt.Sscanf(pair, "%x", &v); err != nil {
		return "0.0"
	}
	return fmt.Sprintf("%.4f", float64(v)/255.0)
}
