package apply

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/convergent-systems-co/branding-library/src/brandatom/internal/client"
)

// EmitCSS writes a `brand-atoms.css` file with custom-property tokens for
// light and dark modes. The file lives next to package.json (or in the
// project root if no package.json exists).
func EmitCSS(brand *client.ResolvedBrand, root string) PlannedWrite {
	dest := filepath.Join(root, "brand-atoms.css")

	light := resolveTokens(brand, "light")
	dark := resolveTokens(brand, "dark")

	var b strings.Builder
	fmt.Fprintf(&b, "/* brand-atoms.css — %s@%s\n", brand.ID, brand.Version)
	fmt.Fprintf(&b, "   Generated by brandatom. Override in your own stylesheet, don't edit. */\n\n")
	b.WriteString(":root {\n")
	for _, t := range light {
		fmt.Fprintf(&b, "  --brandatom-%s: %s;\n", t.key, t.value)
	}
	b.WriteString("}\n\n")
	if len(dark) > 0 {
		b.WriteString("@media (prefers-color-scheme: dark) {\n")
		b.WriteString("  :root {\n")
		for _, t := range dark {
			fmt.Fprintf(&b, "    --brandatom-%s: %s;\n", t.key, t.value)
		}
		b.WriteString("  }\n")
		b.WriteString("}\n")
	}

	return PlannedWrite{
		Path:     dest,
		Contents: []byte(b.String()),
		Kind:     "css",
	}
}

type token struct {
	key   string
	value string
}

// resolveTokens collects the five canonical roles (primary, accent,
// identity, surface, text) for the requested mode.
func resolveTokens(brand *client.ResolvedBrand, mode string) []token {
	roles := []struct {
		out string
		in  string
	}{
		{"primary", "primary"},
		{"accent", "accent"},
		{"identity", "identity"},
		{"surface", "surface"},
		{"background", "background"},
		{"text", "text-primary"},
	}
	tokens := make([]token, 0, len(roles))
	for _, r := range roles {
		hex := brand.RoleHex(r.in, mode)
		if hex == "" && r.in == "identity" {
			// identity falls back to primary, matching brandTheme().
			hex = brand.RoleHex("primary", mode)
		}
		if hex == "" {
			continue
		}
		tokens = append(tokens, token{key: r.out, value: hex})
	}
	return tokens
}
